Korea-Aerospace-University/KAUBOARD

- src/App.scss
- src/components/Clock/Clock.js
- src/components/Clock/Clock.scss
- src/views/Footer/Footer.js
- src/views/Main/Main.js
- src/views/Main/Main.scss
> 중앙 시계 및 슬로건 작업

- src/components/Links/Links.js
- src/components/Links/Links.scss
- src/views/Top/Top.scss
커밋내용
- 상단바 배경색상 추가 (#40368a)
- 링크 컴포넌트 하단 구분선 추가
> 상단바 배경 시그니처 색상 추가

- src/components/IconLink/IconLink.js
- src/components/IconLink/IconLink.scss
- src/components/Links/Links.js
- src/components/Links/Links.scss
아이콘 및 링크 컴포넌트화
-Link에서 ImageLink로 컴포넌트화
-Link.scss에서 content를 ImageLink.scss로 이동
> 아이콘 및 링크 컴포넌트화

- public/index.html
커밋내용
- 새 탭 생성 시 탭 제목 수정
기존 : React App
변경 : 새 탭
> - 새 탭 생성 시 탭 제목 수정

- public/manifest.json
- src/components/Quotes/Quotes.js
커밋내용
- 크롬 저장소 활용을 위한 manifest 파일 수정 
- 명언 목록 중 오타 수정, 너무 길게 표시되는 명언 삭제
> - 크롬 storage api 사용을 위한 manifest 파일 수정

- README.md
커밋내용
- 리드미 소제목 한글화
- 기여자 깃허브 아이디 추가
> 리드미 소제목 한글화

- public/manifest.json
- src/components/Weather/Weather.js
- src/components/Weather/Weather.scss
커밋내용 
- 고양시 화전동 (학교 주소) 날씨 컴포넌트 추가
> 날씨 컴포넌트 추가

- src/components/Weather/Weather.scss
> 날씨 컴포넌트 색상 수정

- src/App.js
- src/components/Quotes/Quotes.scss
- src/components/Weather/Weather.js
- src/components/Weather/Weather.scss
- src/views/Footer/Footer.js
- src/views/Main/Main.js
- src/views/Main/Main.scss
> 메인 뷰 레이아웃 조정

- .gitignore
- src/App.js
- src/App.scss
- src/components/Weather/Weather.js
- src/components/Weather/Weather.scss
- src/views/Footer/Footer.js
- src/views/Main/Main.scss
커밋내용
- 중단 뷰들의 테두리를 둥글게 처리하고 그림자 부여함.
- 기온(숫자) 폰트 변경 (나눔스퀘어 -> noto sans kr)
> 메인 뷰 스타일 변경

- src/components/GeneralNotice/GeneralNotice.js
- src/components/Notice/Notice.js
- src/components/Notice/Notice.scss
- src/views/Main/Main.js
- src/views/Main/Main.scss
- src/views/Top/Top.js
커밋내용
- 공지사항 컴포넌트(with 더미 데이터) 추가 및 스타일 일부 수정
> 공지사항 컴포넌트 추가

- public/loading.svg
- src/components/Notice/Notice.js
- src/components/Weather/Weather.js
- src/components/Weather/Weather.scss
커밋내용
- 날씨 아이콘 배경 추가
- 공지사항 영문 표기 추가
> 날씨 아이콘 배경 추가, 공지사항 영문 표기 추가

- src/components/Notice/Notice.js
- src/components/Notice/Notice.scss
커밋내용
- 학사공지, 일반공지 데이터 연동
- 공지사항은 calm-mesa-43659.herokuapp.com/notification 주소에서 제공합니다.
> 공지사항 데이터 연동

- src/components/CountDown/CountDown.js
- src/components/CountDown/CountDown.scss
- src/components/Notice/Notice.scss
- src/views/Main/Main.js
- src/views/Main/Main.scss
커밋내용
- 종강 / 개강 카운트다운 프로토타입 추가
- 공지사항 컴포넌트 애니메이션 추가
> 종강 카운트다운 프로토타입

- src/components/CountDown/CountDown.js
- src/components/CountDown/CountDown.scss
커밋내용
- 카운트다운 애니메이션 추가
- 약간의 스타일 조정
> 카운트다운 애니메이션 추가

- src/views/Main/Main.js
커밋내용
- Main 컴포넌트 중 사용하지 않는 임포트 삭제
> 불필요한 코드 삭제

- src/components/CheckUpdate/CheckUpdate.js
- src/components/CheckUpdate/CheckUpdate.scss
- src/components/Suggestion/Suggestion.scss
- src/components/Weather/Weather.js
- src/components/Weather/Weather.scss
커밋내용
- 업데이트 확인, 건의사항 아이콘에 호버 애니메이션 추가
- 주간예보 컴포넌트 위치 조정
> 컴포넌트 스타일 수정작업

- src/components/CheckUpdate/CheckUpdate.scss
- src/components/Suggestion/Suggestion.scss
커밋내용
- 제안하기, 업데이트 확인 아이콘 크기 수정
> 제안하기, 업데이트 확인 아이콘 크기 수정

- src/components/Suggestion/Suggestion.js
커밋내용
- 건의사항 제출용 슬랙 웹후크 API 키 수정
> 슬랙 웹후크 API 키 수정

- src/components/CountDown/CountDown.js
커밋내용
- 카운트다운 초기 출력 시 NAN이 출력되던 문제 수정
> 카운트다운 오류 수정

- src/components/Links/Links.js
-> 기존 : https://www.kau.ac.kr/page/main.jsp
변경 : https://www.kau.ac.kr/web/index.do
> feat: 교내 홈페이지 주소 변경에 따른 링크 재설정

- package-lock.json
- package.json
- public/manifest.json
- src/components/Arrow/Arrow.js
- src/components/Arrow/Arrow.scss
- src/components/CheckUpdate/CheckUpdate.js
- src/components/Links/Links.js
- src/components/Notice/Notice.js
- src/components/Virus/Virus.js
- src/components/Virus/Virus.scss
- src/views/Main/Main.js
- 코로나 안정시까지 명언 메뉴를 서울, 경기지역 확진자 메뉴로 대체합니다.
> feat: 명언 메뉴 일시 제거 / 코로나 확진자 메뉴 추가

- src/components/CheckUpdate/CheckUpdate.js
- src/components/Virus/Virus.js
- 코로나 api 요청 주소가 테스트용 로컬 서버로 되어있던 문제 수정
> fix: api 요청 주소 수정
